### ISSUE TITLE
Extending thelibrary

### ISSUE THREAD

**Issue by joeblew99** [kyorohiro/umiuni2d#1]
This is a very impressive proof of the concept. I am trying to compile the flutter app for desktop to see how it performs. Please let me know if you have any suggestions.

**Comment by kyorohiro** [comment]
> >  This is a very impressive proof of the concept. I

Thanks!!

> >  I am trying to compile the flutter app for desktop to see how it performs. 

Umm. I dont know.

# About linux

## ex use flutter run_mojo

http://qiita.com/kyorohiro/items/bd4d8675e934692262ad

Mojo app is executable on linux and android
https://github.com/domokit/mojo

# About mac

Umm. There are signs of building mac app.
- https://github.com/flutter/engine/search?utf8=%E2%9C%93&q=mac
- https://github.com/flutter/game
- https://github.com/flutter/flutter/tree/master/examples/fitness

You try to make build environment. you might build mac app
https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

# About window

Umm. maybe, not support windowns  platofrom now.
https://github.com/flutter/flutter/issues/138

**Comment by joeblew99** [comment]
Thanks. 
Are you looking for work ?

**Comment by joeblew99** [comment]
I work with a gaijin, that speaks Japanese here, if it helps

**Comment by kyorohiro** [comment]
> > Are you looking for work ?
> > I work with a gaijin, that speaks Japanese here, if it helps

Thanks!
But, My status is very busy  for my some projects now.
So, Work is the last thing now.

Honestly, I’m broke now. 
It's ok. No problem.

**Comment by joeblew99** [comment]
Ok dude. Good luck with it all. I used to live in Kobe years ago, and will be going back next month to Tokyo. Let me know if you want to chat and talk projects, etc.

**Comment by kyorohiro** [comment]
ok!! see you!!
